builds:
  - binary: keyvault-certdeploy
    ldflags:
      - -s -w -X github.com/emgag/keyvault-certdeploy/internal/lib/version.Version={{.Version}} -X github.com/emgag/keyvault-certdeploy/internal/lib/version.Commit={{.Commit}} -X github.com/emgag/keyvault-certdeploy/internal/lib/version.Date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
archive:
  format: tar.gz
  files:
    - LICENSE
